version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - maintenance
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    labels:
      - github-actions
      - maintenance
