export function pct(value,total){return total?Math.round(value/total*100):0}
export function isCurrentPrediction(prediction){return prediction?.isCurrentPrice===true||typeof prediction?.latestObservationAgeHours==='number'&&prediction.latestObservationAgeHours<=2}
export function successfulScrapeAt(station){return station?.lastSuccessfulScrapeAt||(!station?.lastScrapeBlocked&&station?.lastScrapedAt)||null}
export function stateCounts(stations){const map=new Map();for(const s of stations||[]){const key=s.state||'Unknown';map.set(key,(map.get(key)||0)+1)}return[...map.entries()].map(([state,count])=>({state,count})).sort((a,b)=>b.count-a.count)}
export function coverageKpis(stations,predictions){const total=stations.length;const priced=new Set((predictions||[]).map(p=>p.stationId)).size;const coords=stations.filter(s=>typeof s.lat==='number'&&typeof s.lng==='number').length;const teslaUrls=stations.filter(s=>String(s.url||'').includes('tesla.com/findus')).length;const checked=stations.filter(successfulScrapeAt).length;const withPrice=stations.filter(s=>s.lastScrapeHadPrice&&!s.lastScrapeBlocked).length;return{total,priced,pricedPct:pct(priced,total),coords,coordsPct:pct(coords,total),teslaUrls,teslaUrlPct:pct(teslaUrls,total),scraped:checked,scrapedPct:pct(checked,total),checked,checkedPct:pct(checked,total),withPrice,withPricePct:pct(withPrice,total)}}
export function pricingStats(predictions){const vals=(predictions||[]).filter(p=>p.membershipType==='member'&&typeof p.expectedPrice==='number').map(p=>p.expectedPrice).sort((a,b)=>a-b);if(!vals.length)return{count:0,low:null,median:null,high:null,avg:null};const avg=vals.reduce((a,b)=>a+b,0)/vals.length;return{count:vals.length,low:vals[0],median:vals[Math.floor(vals.length/2)],high:vals[vals.length-1],avg}}
export function currentPricingStats(predictions){return pricingStats((predictions||[]).filter(isCurrentPrediction))}
export function topStates(stations,limit=12){return stateCounts(stations).slice(0,limit)}
export function refreshQueueStates(stations,limit=12){const map=new Map();const now=Date.now();for(const s of stations||[]){const state=s.state||'Unknown';const row=map.get(state)||{state,needsRefresh:0,unchecked:0,stale:0,blocked:0,priceHidden:0,total:0};const scrapedAt=successfulScrapeAt(s);row.total+=1;if(s.lastScrapeBlocked)row.blocked+=1;if(!scrapedAt){row.unchecked+=1;row.needsRefresh+=1}else{const ageHours=(now-new Date(scrapedAt).getTime())/36e5;if(!Number.isFinite(ageHours)||ageHours>48){row.stale+=1;row.needsRefresh+=1}}if(scrapedAt&&!s.lastScrapeHadPrice)row.priceHidden+=1;map.set(state,row)}return[...map.values()].filter(row=>row.needsRefresh>0||row.priceHidden>0).sort((a,b)=>b.needsRefresh-a.needsRefresh||b.blocked-a.blocked||b.priceHidden-a.priceHidden||b.total-a.total).slice(0,limit)}
export function scrapeOutcome(stations){const blocked=stations.filter(s=>s.lastScrapeBlocked).length;const price=stations.filter(s=>s.lastScrapeHadPrice&&!s.lastScrapeBlocked).length;const availability=stations.filter(s=>s.lastScrapeHadAvailability&&!s.lastScrapeHadPrice&&!s.lastScrapeBlocked).length;const checkedNoPrice=stations.filter(s=>s.lastScrapedAt&&!s.lastScrapeHadPrice&&!s.lastScrapeHadAvailability&&!s.lastScrapeBlocked).length;const notChecked=stations.filter(s=>!s.lastScrapedAt&&!s.lastScrapeBlocked).length;return[{name:'Price found',count:price},{name:'Availability only',count:availability},{name:'Blocked',count:blocked},{name:'No price shown',count:checkedNoPrice},{name:'Not checked yet',count:notChecked}]}
